#numpy array operation

In [3]:
import numpy as np

arr =np.array([1,2,3,4,5,6,7,8,9,10])
print("basic sclicing",arr[3:8])
print("slcing with steps",arr[2:7:2])
print("-ve index",arr[-5])


basic sclicing [4 5 6 7 8]
slcing with steps [3 5 7]
-ve index 6


#2d array slicing

In [14]:
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("specific element",arr2d[2,1])
print("entir row",arr2d[1])
print("entir column",arr2d[:,1])

specific element 8
entir row [4 5 6]
entir column [2 5 8]


#SORTING

In [22]:
unsorted =np.array([1,2,5,4,3,6,7,8,9,10])
print("sorted array",np.sort(unsorted))


arr2d_unsorted=np.array([[2,3],[1,5],[6,8]])
print("sorted 2d array by row",np.sort(arr2d_unsorted,axis=1))

sorted array [ 1  2  3  4  5  6  7  8  9 10]
sorted 2d array by row [[2 3]
 [1 5]
 [6 8]]


#filtering in array

In [23]:
#basic 
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
even_numbers=numbers[numbers%2 == 0]
print("even numbers",even_numbers)





even numbers [ 2  4  6  8 10]


#filter with mask

In [26]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])

mask = numbers> 6
print("numbers greater than 6",numbers[mask])

numbers greater than 6 [ 7  8  9 10]


#Fancy indexing vs np.where()

In [29]:
numbers=np.array([1,2,3,4,5,6,7,8,9,10])
indices =[0,3,5]
print(numbers[indices])

# use with where

where_result =np.where(numbers >5)
print("np where",numbers[where_result])


[1 4 6]
np where [ 6  7  8  9 10]


In [31]:
a=np.array([1,2,3,4])
b=np.array([1,2,3,4])
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))
print(np.mod(a,b))

[2 4 6 8]
[0 0 0 0]
[ 1  4  9 16]
[1. 1. 1. 1.]
[0 0 0 0]
