#creating array from list

#numpy basics


In [1]:
# numpy basics
import numpy as np
arr_1d=np.array([1,2,4])
print(arr_1d)

[1 2 4]


#2d array

In [2]:
# 2d array
import numpy as np
arr_2d = np.array([[1,2,3],[4,5,6]])
print(arr_2d)

[[1 2 3]
 [4 5 6]]


#list vs numpy array

In [ ]:
list =[1,2,3]
print(list*2)

np_array =np.array([1,2,3])#element wise multiplication
print(np_array*2)

import time
start = time.time()
list =[i*2 for i in range(100)]
print(time.time()-start)


start = time.time()
np_array=np.arange(100)*2



[1, 2, 3, 1, 2, 3]
[2 4 6]
0.00010418891906738281
[[0.01578999 0.40797441 0.04297827]
 [0.00468992 0.43170484 0.05094938]]


#creating array from scratch

In [3]:
import numpy as np
zeros= np.zeros((3,4))#[1,2]
print(zeros)

ones = np.ones((2,3))
print(ones)

full =np.full((2,2),7)
print(full)


random = np.random.random((2,3))
print(random)


sequence =np.arange(0,10,2)
print(sequence)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[7 7]
 [7 7]]
[[0.76068249 0.66409413 0.72620249]
 [0.73762163 0.5806286  0.90232206]]
[0 2 4 6 8]


# vector , martices , tensor 

In [ ]:
import numpy as np
vector = np.array([1,2,3])
print(vector)

matrix =np.array([[1,2,3],  [4,5,6]])
print(matrix)


tensor = np.array([[[1,2],[3,4]],
                   [[5,6],[7,8]]])
print("tensor",tensor)

[1 2 3]
[[1 2 3]
 [4 5 6]]
tensor [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


#array propites

In [25]:
array =np.array([[1,2,3],[4,5,6]])
print("shape of array",array.shape)
print("dimennsion of array",array.ndim)
print("size of array",array.size)
print("data type",array.dtype)


shape of array (2, 3)
dimennsion of array 2
size of array 6
data type int64


#array reshaping

In [43]:
arr = np.arange(12)
print("orginal array",arr)

# reshape 
reshaped = arr.reshape((3,4))
print("\nreshaped",reshaped)

# flattened
flattened = reshaped.flatten()
print("flattened",flattened)

# raveled array returns view instead of copy
raveled = reshaped.ravel()
print("ravel",raveled)


# transpose
transpose = reshaped.T
print("transpose",transpose)

orginal array [ 0  1  2  3  4  5  6  7  8  9 10 11]

reshaped [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
flattened [ 0  1  2  3  4  5  6  7  8  9 10 11]
ravel [ 0  1  2  3  4  5  6  7  8  9 10 11]
transpose [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
